export const NOTES = [
  { key: "v",  note: "F",  octave: 3, freq: 174.61, type: "white" },
  { key: ",",   note: "F#", octave: 3, freq: 185.00, type: "black" },
  { key: "b",  note: "G",  octave: 3, freq: 196.00, type: "white" },
  { key: ".",   note: "G#", octave: 3, freq: 207.65, type: "black" },
  { key: "n",  note: "A",  octave: 3, freq: 220.00, type: "white" },
  { key: "/",   note: "A#", octave: 3, freq: 233.08, type: "black" },
  { key: "m",  note: "B",  octave: 3, freq: 246.94, type: "white" },

  { key: "a",  note: "C",  octave: 4, freq: 261.63, type: "white" },
  { key: "w",  note: "C#", octave: 4, freq: 277.18, type: "black" },
  { key: "s",  note: "D",  octave: 4, freq: 293.66, type: "white" },
  { key: "e",  note: "D#", octave: 4, freq: 311.13, type: "black" },
  { key: "d",  note: "E",  octave: 4, freq: 329.63, type: "white" },
  { key: "f",  note: "F",  octave: 4, freq: 349.23, type: "white" },
  { key: "t",  note: "F#", octave: 4, freq: 369.99, type: "black" },
  { key: "g",  note: "G",  octave: 4, freq: 392.00, type: "white" },
  { key: "y",  note: "G#", octave: 4, freq: 415.30, type: "black" },
  { key: "h",  note: "A",  octave: 4, freq: 440.00, type: "white" },
  { key: "u",  note: "A#", octave: 4, freq: 466.16, type: "black" },
  { key: "j",  note: "B",  octave: 4, freq: 493.88, type: "white" },

  { key: "k",  note: "C",  octave: 5, freq: 523.25, type: "white" },
  { key: "o",  note: "C#", octave: 5, freq: 554.37, type: "black" },
  { key: "l",  note: "D",  octave: 5, freq: 587.33, type: "white" },
  { key: "p",  note: "D#", octave: 5, freq: 622.25, type: "black" },
  { key: ";",  note: "E",  octave: 5, freq: 659.25, type: "white" },
  { key: "'",  note: "F",  octave: 5, freq: 698.46, type: "white" },
  { key: "[",  note: "F#", octave: 5, freq: 739.99, type: "black" },
];